version: '2'
services:
    jhipster5sampleapplication-app:
        image: jhipster5sampleapplication
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipster5sampleapplication-postgresql:5432/jhipster5SampleApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipster5sampleapplication-elasticsearch:9300
        ports:
            - 8080:8080
    jhipster5sampleapplication-postgresql:
        extends:
            file: postgresql.yml
            service: jhipster5sampleapplication-postgresql
    jhipster5sampleapplication-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipster5sampleapplication-elasticsearch
