version: '2'
services:
    jhipster5sampleapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipster5SampleApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipster5SampleApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
